[package]
name = "screentime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.27.0"
chrono = "0.4.22"
dirs = "4.0.0"
jsonrpc-http-server = "18.0.0"
rdev = "0.5.1"
crossbeam = "0.8.2"
reqwest = { version = "0.11.2", features = ["blocking"] }
tiny_http = "0.11.0"
mockall = "0.11.2"
