[package]
name = "screentime"
version = "0.1.1"
edition = "2021"
authors = ["Piotr Czajka <czajka@protonmail.com>"]
license= "MIT"
keywords = ["utility", "command-line-tool", "screentime"]
categories = ["command-line-utilities"]
description = "A lightweight screentime monitoring tool"
repository = "https://github.com/Ginkooo/screentime"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
dirs = "4.0.0"
rdev = "0.5.1"
tiny_http = "0.11.0"
